### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [Onix-Systems/RainyRefreshControl#15]
<img width="501" alt="screen shot 2016-12-11 at 1 16 44 am" src="https://cloud.githubusercontent.com/assets/6511079/21079210/80c75616-bf3f-11e6-8317-5011cc2f0e61.png">

**Comment by lfarah** [comment]
https://github.com/vsouza/awesome-ios/pull/1379

**Comment by derpoliuk** [comment]
Done:

<img width="626" alt="screen shot 2017-01-10 at 1 07 08 pm" src="https://cloud.githubusercontent.com/assets/1434418/21804064/b4520fcc-d735-11e6-9e7b-13f083cbfe2b.png">
