### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [Onix-Systems/RainyRefreshControl#16]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by dolzhenko-tony** [comment]
Thanx, @lfarah! We will keep updating README while adding features/refactoring project. Please, check our pull request to "Awesome iOS" list: https://github.com/vsouza/awesome-ios/pull/1379

**Comment by dolzhenko-tony** [comment]
@lfarah , thanx for good article!
